import { useState } from 'react';
import { AnimatePresence, motion, useReducedMotion } from 'motion/react';
import { Check, LayoutDashboard } from 'lucide-react';
import { Card } from '../ui/Card';
import { features, landingCopy } from '../../constants/landing';

function Preview({ title, description, className = '' }: { title: string; description: string; className?: string }) { return <div className={`flex aspect-16/10 flex-col items-center justify-center border-2 border-dashed border-grey-04 bg-grey-02 p-6 text-center text-text-secondary ${className}`}><span className='text-4xl'>▧</span><strong className='mt-4 text-lg text-text-primary'>{title}</strong><span className='mt-2 max-w-xs text-sm'>{description}</span></div>; }

export function FeatureSection() {
  const [active, setActive] = useState(0); const reduceMotion = useReducedMotion(); const feature = features[active];
  return <section id='features' className='mx-auto max-w-6xl border-b border-grey-02 px-5 py-20 lg:px-8 lg:py-28'><div className='mb-10'><span className='text-xs font-semibold uppercase tracking-[0.16em] text-brand-01'>{landingCopy.featuresEyebrow}</span><h2 className='type-heading mt-4 max-w-2xl text-4xl'>{landingCopy.featuresTitle}</h2></div><Card className='mb-6 grid gap-8 border border-grey-02 bg-core-white sm:grid-cols-[0.8fr_1.2fr]'><div><span className='mb-4 inline-flex rounded-full bg-brand-01 p-3 text-core-white'><LayoutDashboard size={18} /></span><h3 className='type-title'>{landingCopy.dashboardTitle}</h3><p className='mt-2 text-sm text-text-secondary'>{landingCopy.dashboardText}</p></div><ul className='space-y-3 text-sm'>{landingCopy.dashboardBullets.map(item => <li className='flex items-center gap-3' key={item}><span className='rounded-full bg-feedback-positive p-1 text-core-white'><Check size={12} /></span>{item}</li>)}</ul></Card><div className='grid gap-6 lg:grid-cols-[1.1fr_0.9fr]'><div className='grid grid-cols-2 gap-3'>{features.map(({ title, text, Icon }, index) => <button aria-label={title} type='button' className={`rounded-soft border p-5 text-left transition-colors ${active === index ? 'border-brand-01 bg-core-white' : 'border-grey-02 hover:border-grey-03'}`} onClick={() => setActive(index)} key={title}><span className={`mb-4 inline-flex rounded-full p-2.5 ${active === index ? 'bg-brand-01 text-core-white' : 'bg-grey-02 text-brand-01'}`}><Icon size={18} /></span><h3 className='font-semibold'>{title}</h3><p className='mt-2 text-sm leading-relaxed text-text-secondary'>{text}</p></button>)}</div><AnimatePresence mode='wait' initial={false}><motion.div key={feature.title} initial={reduceMotion ? false : { opacity: 0, x: 10 }} animate={{ opacity: 1, x: 0 }} exit={reduceMotion ? undefined : { opacity: 0, x: -10 }} transition={{ duration: 0.22 }}><Preview title={feature.title} description={feature.detail} className='h-full aspect-auto' /></motion.div></AnimatePresence></div></section>;
}
